#!/usr/bin/env python3
"""build-country-polygons.py

Downloads Natural Earth Admin 0 country polygons and converts them into the
same compact JS format used by this project.

Output:
	src/data/countries-natural-earth.js

Notes:
	- This script is optional. The app will fall back to the manual polygons in
	  src/data/countries-natural-earth.js.
	- No external python packages are required.
"""

import json
import sys
import urllib.request


NE_GEOJSON_URL_110M = (
	'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson'
)
NE_GEOJSON_URL_50M = (
	'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_admin_0_countries.geojson'
)

OUTPUT_PATH = 'src/data/countries-natural-earth.js'


def fetch_json(url):
	with urllib.request.urlopen(url) as r:
		data = r.read().decode('utf-8')
		return json.loads(data)


def iter_rings(geom):
	gt = geom.get('type')
	coords = geom.get('coordinates')
	if not gt or coords is None:
		return
	if gt == 'Polygon':
		# coords: [ [ [lng,lat], ... ], [hole], ... ]
		# Keep only the exterior ring at index 0.
		if coords and coords[0]:
			yield coords[0]
		return
	if gt == 'MultiPolygon':
		# coords: [ polygon, polygon, ... ]
		for poly in coords:
			if poly and poly[0]:
				yield poly[0]


def clamp_precision(pt, decimals):
	lng = round(float(pt[0]), decimals)
	lat = round(float(pt[1]), decimals)
	return [lng, lat]


def main():
	url = NE_GEOJSON_URL_110M
	decimals = 4
	if '--50m' in sys.argv:
		url = NE_GEOJSON_URL_50M
		decimals = 5
	data = fetch_json(url)
	features = data.get('features') or []

	out = []
	for f in features:
		props = f.get('properties') or {}
		name = props.get('NAME') or props.get('ADMIN') or props.get('name')
		geom = f.get('geometry') or {}
		if not name:
			continue
		polys = []
		for ring in iter_rings(geom):
			if not ring or len(ring) < 4:
				continue
			# Drop the final point if it duplicates the first.
			if ring[0][0] == ring[-1][0] and ring[0][1] == ring[-1][1]:
				ring = ring[:-1]
			polys.append([clamp_precision(p, decimals) for p in ring])
		if not polys:
			continue
		out.append({'name': name, 'polys': polys})

	out.sort(key=lambda x: x['name'])

	js = []
	js.append('// countries-natural-earth.js')
	js.append('// Generated by scripts/build-country-polygons.py')
	js.append("// Source: Natural Earth Admin 0 Countries")
	js.append('')
	js.append("C.COUNTRY_POLYGONS_SOURCE = 'naturalearth';")
	js.append('C.COUNTRY_POLYGONS = [')
	for i, c in enumerate(out):
		name_json = json.dumps(c['name'], ensure_ascii=True, separators=(',', ':'))
		polys_json = json.dumps(c['polys'], ensure_ascii=True, separators=(',', ':'))
		js.append('\t{')
		js.append('\t\t"name":' + name_json + ',')
		js.append('\t\t"polys":' + polys_json)
		js.append('\t}' + (',' if i < len(out) - 1 else ''))
	js.append('];')
	js.append('')

	with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
		f.write('\n'.join(js))

	print('Wrote', OUTPUT_PATH, 'countries:', len(out))


if __name__ == '__main__':
	main()
